In [2]:
# design sprial star
import turtle  as t
a1 =t.Turtle()
a1.pencolor('blue')
for i in range (50):
    a1.forward(i * 10)
    a1.left(144)
t.done()

Terminator: 

In [ ]:
# Design  sprial
import turtle as t
a1 = t.Turtle()
a1.pencolor('red')
for i in range (200):
    a1.forward(i)
    a1.left(91)
a1.done()


In [4]:
#  design  hexagon
import turtle as t
a1=t.Turtle()
a1.pencolor('red','yellow','orange','blue','violet')
for i in range (360):
    pencolor(colors[i%6])
    width(i/100+1)
    forward(i)
    left(59)


TurtleGraphicsError: bad color arguments: ('red', 'yellow', 'orange', 'blue', 'violet')

In [7]:
# design circle
from turtle import*
pensize(3)
pencolor('red')
for i in range(15):
    circle (10*i)

In [ ]:
# design circle
from turtle import*
pensize(5)
pencolor('red')
fillcolor('blue')
begin_fill()
circle(100)
end_fill()


In [ ]:
# design sprial circle
from turtle import *
pensize(3)
pencolor('orange')
for i in range(100):
    circle(10+i,45)

In [1]:
#### design circle
from turtle import*
pensize(3)
colors = ['blue','green','red','orange']
for i in range(30):
    pencolor(colors[i%4])
    circle(10*i)
    up()
    sety((10 *i)*(-1))
    down()

In [8]:
# design olympics logo 
from turtle import *
pensize(6)
r1 = ["blue","black","red"]
for i in range(3):
    penup()
    pencolor(r1[i%3])
    goto(i*100,0)
    pendown()
    circle(45)
r2 = ["","yellow","","green"]
for i in range(1,4,2):
    penup()
    pencolor(r2[i])
    goto(i*55 ,-55)
    pendown()
    circle(50)


In [2]:
# design Audi logo
from turtle import *
pensize(6)
pencolor('black')
for i in range (4):
    penup()
    goto(i*70,0)
    pendown()
    circle(50)
    

In [ ]:
from turtle  impo2rt *
bgcolor('green')
color('#2B28F6')
Fillcolor('#2B28F6')
turtl

In [1]:
# import turtle library
import turtle             
colors = [ "red","purple","blue","green","orange","yellow"]
my_pen = turtle.Pen()
turtle.bgcolor("black")
for x in range(360):
   my_pen.pencolor(colors[x % 6])
   my_pen.width(x/100 + 1)
   my_pen.forward(x)
   my_pen.left(59)


Terminator: 

In [2]:
import turtle
 
car = turtle.Turtle()
 
#Below code for drawing rectanglura upper body
car.color('#2B2BF6')
car.fillcolor('#2B2BF6')
car.penup()
car.goto(0,0)
car.pendown()
car.begin_fill()
car.forward(370)
car.left(90)
car.forward(50)
car.left(90)
car.forward(370)
car.left(90)
car.forward(50)
car.end_fill()
 
#Below code for drawing window and roof
car.penup()
car.goto(100, 50)
car.pendown()
car.setheading(45)
car.forward(70)
car.setheading(0)
car.forward(100)
car.setheading(-45)
car.forward(70)
car.setheading(90)
car.penup()
car.goto(200, 50)
car.pendown()
car.forward(49.50)
 
#Below code for drawing two tyres
car.penup()
car.goto(100, -10)
car.pendown()
car.color('#000000')
car.fillcolor('#000000')
car.begin_fill()
car.circle(20)
car.end_fill()
car.penup()
car.goto(300, -10)
car.pendown()
car.color('#000000')
car.fillcolor('#000000')
car.begin_fill()
car.circle(20)
car.end_fill()
 
car.hideturtle()

### idiomatic python
- transformation code into beautiful, idiomatic python
-  replace traditional index manipulation with python code looping idioms


In [4]:
# looping over a range of number 
for i in [0,1,2,3,4,5]:
    print(i**2,end=' ')
    
print()
#pythinic-way
for i in range(6):
    print(i**2,end=' ')
    

0 1 4 9 16 25 
0 1 4 9 16 25 

In [5]:
#looping over the collection(list)
li =[1,2,3,4,5]
for i in range (len(li)):
    print(li[i],end=' ')
print()
#pythonic-way
for i in li:
    print(i,end=' ')
    

1 2 3 4 5 
1 2 3 4 5 

In [6]:
#loopinf from backwards
li = [1,2,3,4,5]
for i in range(len(li)-1,-1,-1):
    print(li[i],end=' ')
print()
#pythonic-way
for i in reversed(li):
    print(i,end=' ')
    
    
    
    

    

5 4 3 2 1 
5 4 3 2 1 

In [8]:
#looping over the collection with index
li= [1,2,3,4,5]
for i in range (len(li)):
    print(i,'-->',li[i])
print()
#pythonic-way
for i ,a in enumerate(li):
    print(i,'-->',a)
    

0 --> 1
1 --> 2
2 --> 3
3 --> 4
4 --> 5

0 --> 1
1 --> 2
2 --> 3
3 --> 4
4 --> 5


In [11]:
#looping over two collections
li =[1,2,3,4,5]
a = [1,2,3,4,5,6,6,8]
n = min(len(li), len(a))
for i in  range(n):
    print(li[i], ' ', a[i])
print()
#pythonic-way
for i ,a in zip (li,a):
    print(i,' ',a)


1   1
2   2
3   3
4   4
5   5

1   1
2   2
3   3
4   4
5   5


In [12]:
#  looping in sorted order
li = [8,1,25,16,9,2]
for i in sorted(li):
    print(i, end=' ')
    
print()
for i in sorted(li,reverse=True):
    print(i,end=' ')

1 2 8 9 16 25 
25 16 9 8 2 1 

In [13]:
#dictionary
d ={'name':'gitam','emailid':'gitam@gitam.edu','address':'vizag'}
for k in d:
    print(k,end=' ')
print()

name emailid address 


In [17]:
for k in d.keys():
    if k.startswith('A')
       del d[k]

SyntaxError: invalid syntax (<ipython-input-17-d81572cf351e>, line 2)

In [18]:
# traditional approch
li = []
for i in  range(10):
    a = i **2
    li.append(a)
print(sum(li))
print()
#rpythonicc-way
print(sum(i**2 for i in range(10)))


285

285


In [19]:
li = []
for i in range(10):
    li.append(i**2)
li

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [20]:
com_list =[i **2 for i in range(10)]
com_list


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [21]:
for i in li:
    if i%2== 0:
        print(i,end= "")

04163664

In [22]:
cpm_list= [i%2=0 for i in li ]
com_list

SyntaxError: invalid syntax (<ipython-input-22-b73d0260cb7d>, line 1)

In [ ]:
####lambda
-   the lambda keyword is used to create anonymous functions. 

## lambda using filter()
- The filter() function in Python takes in a function and a list as arguments. 
-  This offers an elegant way to filter out all the elements of a sequence “sequence”, for which the function returns True

In [24]:
def filterlist(li):
    a = []
    for i in li:
        if i % 2 == 0:
            a.append(i)
    return a
li = [1,2,3,4,5,6,7,8]
filterlist(li)

[2, 4, 6, 8]

In [25]:
li = [1,2,3,4,5,6,7,8]
lam_li = list(filter(lambda x : (x%2==0), li))
print(lam_li)


[2, 4, 6, 8]


## Lambda using map()
- The map() function in Python takes in a function and a list as argument. 
-  The function is called with a lambda function and a list and a new list is returned which contains all the lambda modified items returned by that function for each item.

In [32]:
def  squarelist(li):
    a = []
    for i in li:
        a.append(i*2)
    return a
    li = [1,2,3,4,5,6,7,8]
squarelist(li)

[2, 4, 6, 8, 10, 12, 14, 16]

In [34]:
li = [1,2,3,4,5,6,7,8]
map_list = list(map(lambda x : x*2,li))
print(map_list)

[2, 4, 6, 8, 10, 12, 14, 16]


#  lambda with replace ()
- The reduce() function in Python takes in a function and a list as argument. 
- The function is called with a lambda function and a list and a new reduced result is returned. 
- This performs a repetitive operation over the pairs of the list. 


In [41]:
def sumlist(li):
    s=0
    for i in li:
        s += i
    return s
li = [1,2,3,4,5,6,7,8]
sumlist(li)

36

In [ ]:
from functio import reduce
li = [1,2,3,4,5,6,7,8]
s = reduce

### standard package 
## pandas, numpy and matplotib

# pandas
- data cleaning
- data transformation
- data analysis
## notation
- series
- dataframe
#### Series:
 -  Series is one dimensional(1-D) array defined in pandas that can be used to store any data type.
 ### dataframe
- DataFrames is two-dimensional(2-D) data structure defined in pandas which consists of rows and columns.
  

In [1]:
import pandas as pd
internal1 ={'s1':35,'s2':35,'s3':35}
internal2 ={'s1':45,'s2':45,'s3':45}
internal1 = pd.Series(internal1)
internal2 =pd.Series(internal2)
print(internal1)
print(internal2)


s1    35
s2    35
s3    35
dtype: int64
s1    45
s2    45
s3    45
dtype: int64


In [3]:
final = {'internal1':internal1,'internal2':internal2}
final =pd.DataFrame(final)
print(final)

    internal1  internal2
s1         35         45
s2         35         45
s3         35         45


In [4]:
final.columns # return  the names of column


Index(['internal1', 'internal2'], dtype='object')

In [5]:
final.values #return all rows values in 2 dimensional array


array([[35, 45],
       [35, 45],
       [35, 45]], dtype=int64)

In [6]:
final.values[1] # 1 reoresents the row 

array([35, 45], dtype=int64)

In [8]:
final.values[2][0] = 350 # update the dataframe values

In [9]:
final.values

array([[ 35,  45],
       [ 35,  45],
       [350,  45]], dtype=int64)

In [10]:
for row in final.values:
    print('internal1 -',row[0],'internals2 -' , row[1])

internal1 - 35 internals2 - 45
internal1 - 35 internals2 - 45
internal1 - 350 internals2 - 45


In [11]:
final.loc['s4'] = [20,18] #insert the row records inthe dataframe
final

internal1  internal2
s1         35         45
s2         35         45
s3        350         45
s4         20         18

In [12]:
final.values[2]=[155,255]
final

internal1  internal2
s1         35         45
s2         35         45
s3        155        255
s4         20         18

In [13]:
pwd


'C:\\Users\\dell'

In [14]:
df = pd.read_csv("Income.csv")
df

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [15]:
# extract income of all states in year 2013
# Alabama : 41381
#.........
for row in df.values:
    print(row[1],' : ',row[-1])


Alabama  :  41381
Alaska  :  61137
Arizona  :  50602
Arkansas  :  39919
California  :  57528


In [17]:
# average income of california
def avgofstate():
    s = 0
    for i in range(2,11):
        s += df.values[4][i]
        return s // len (df.values[4][2:])
avgofstate()

5750

In [ ]:

# function which only displays the column names in the list
#GEOID state 2005 2006 2007 2008 2009 2010 2011 2012 2013 
def printdataframecolumn(df):
    li = []
    columns =df.columns
    for i in columns:
        li.append(i)
        return li
printdataframecolunmns()

In [18]:
df.shape

(5, 11)

In [19]:
df.head()


GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [20]:
df.tail()


GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [21]:
# describe () , min,max,counint,mean and etc
df.describe()

2005          2006          2007          2008         2009  \
count      5.000000      5.000000      5.000000      5.000000      5.00000   
mean   45339.800000  46680.600000  52945.400000  50395.800000  47999.00000   
std     8586.880615   9195.672966  10868.796129   9906.997487  10630.62477   
min    36658.000000  37057.000000  40795.000000  39586.000000  36538.00000   
25%    37150.000000  37952.000000  42212.000000  44476.000000  39980.00000   
50%    45245.000000  46657.000000  55734.000000  46914.000000  45739.00000   
75%    51755.000000  55319.000000  62993.000000  57014.000000  56134.00000   
max    55891.000000  56418.000000  62993.000000  63989.000000  61604.00000   

               2010          2011          2012          2013  
count      5.000000      5.000000      5.000000      5.000000  
mean   47709.400000  48662.200000  50038.800000  50113.400000  
std     8303.656201   6893.345538  10094.581873   9446.102122  
min    38587.000000  41302.000000  39018.000000  39919.000000  
25%    40933.000000  42590.000000  43464.000000  41381.000000  
50%    46896.000000  48621.000000  47044.000000  50602.000000  
75%    54283.000000  53367.000000  57020.000000  57528.000000  
max    57848.000000  57431.000000  63648.000000  61137.000000

In [22]:
# convert all column names into list 
df.columns.tolist()

['GEOID',
 'State',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013']

In [23]:
df.max()


GEOID     04000US06
State    California
2005          55891
2006          56418
2007          62993
2008          63989
2009          61604
2010          57848
2011          57431
2012          63648
2013          61137
dtype: object

In [24]:
df['Lteam'].max()

KeyError: 'Lteam'

In [25]:
df['Lteam'].min()

KeyError: 'Lteam'

In [26]:
df.loc[:3]

GEOID     State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01   Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02    Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04   Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05  Arkansas  36658  37057  40795  39586  36538  38587  41302   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919

In [27]:
df.iloc[:3]

GEOID    State   2005   2006   2007   2008   2009   2010   2011   2012  \
0  04000US01  Alabama  37150  37952  42212  44476  39980  40933  42590  43464   
1  04000US02   Alaska  55891  56418  62993  63989  61604  57848  57431  63648   
2  04000US04  Arizona  45245  46657  62993  46914  45739  46896  48621  47044   

    2013  
0  41381  
1  61137  
2  50602

In [28]:
df .sort-values('Lscore').head()

AttributeError: 'DataFrame' object has no attribute 'sort'

In [29]:
df[df['state']]

KeyError: 'state'